services:
  - type: web
    name: nexus
    runtime: docker
    plan: starter
    region: frankfurt
    branch: main
    rootDir: .
    healthCheckPath: /api/health
    autoDeploy: true
    disk:
      name: nexus-data
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: DATA_DIR
        value: /var/data
      - key: DEBUG
        value: "false"
      - key: SECRET_KEY
        generateValue: true
      - key: TOCONLINE_CLIENT_ID
        sync: false
      - key: TOCONLINE_CLIENT_SECRET
        sync: false
      - key: TOCONLINE_OAUTH_URL
        value: https://identity.toconline.pt
      - key: TOCONLINE_API_URL
        value: https://apiv1.toconline.com
